### ISSUE TITLE
Remote Reference – $ref

### ISSUE THREAD

**Issue by dolalla** [ForAllSecure/mapi-action#108]
Hi Team,
I'm getting an issue in my openapi 3.0.0 file when I run Mayhem for API to check for vulnerabilities. This is the issue:

`FATAL  Failed to fuzz target - Specification error: Unsupported specification: Unsupported path reference ./paths/cards.yaml# for /accounts/{accountId}/cards `

The api-spec file looks like this:

```
  /accounts/{accountId}/cards:
    $ref: './paths/cards.yaml#/cards'
```

Can't I use $Ref: ??

**Comment by alpire** [comment]
@dolalla: Mayhem for API currently does not support references containing URIs that point to another file or a remote location. If this is a must have for you, we might be able to add that feature, but I'd have to check internally.

**Comment by dolalla** [comment]
@alpire Thanks for your answer. 
We are considering/evaluating you software for our organization, but honetlly, this is a big limitation for us. We have external references in our openapi files for all our projects and we can't rebuild all that.

**Comment by alpire** [comment]
@dolalla: Totally understand how big of a limitations this is for you. You shouldn't have to rebuild your specs to use the tool obviously.

During the evaluation period, would you be able to use open source tools to resolve the $ref's, like https://github.com/wework/speccy#resolve-command? And if you decide to move forward with a mapi purchase, we'll add that feature directly into our CLI.

**Comment by jehrlich** [comment]
How about using the Redoc CLI to bundle refs into a single file https://github.com/Redocly/redoc/tree/master/cli

**Comment by xansec** [comment]
Minor update - the above Github link no longer works. Here's one that does:
https://github.com/Redocly/redoc/blob/8c391497bf5b8445251cb55f8705f54bfbfdad80/docs/deployment/cli.md
